function Data(id, name, color, category, subCategory, price, img, size) {
    function createData(id, name, color, category, subCategory, price, img, size) {
        return {
            id,
            name,
            color,
            category,
            subCategory,
            price,
            img,
            size,
        };
    }

    return createData(id, name, color, category, subCategory, price, img, size);
}

export const products = [
    Data(1, 'Giày Superstar', 'white', 'giay_nam', 'originals', 108.75, ['Giày Superstar.jpg'], 40),
    Data(2, 'Giày Continental 80', 'white', 'giay_nu', 'originals', 109, ['Giày Continental 80.jpg'], 41),
    Data(3, 'Giày Nizza', 'red', 'giay_nam', 'originals', 144.99, ['Giày Nizza.jpg'], 42),
    Data(4, 'adiFOM SLTN', 'black', 'giay_nam', 'originals', 69.99, ['adiFOM SLTN.jpg'], 43),
    Data(5, 'Giày Haiwee', 'white', 'giay_nam', 'originals', 23.99, ['Giày Haiwee.jpg'], 44),
    Data(
        6,
        'Giày Sport Pro adidas x LEGO®',
        'yellow',
        'giay_tre_em',
        'thethao',
        17.99,
        ['Giày Sport Pro adidas x LEGO®.jpg'],
        39,
    ),
    Data(
        7,
        'Giày Tập Thể Thao Có Quai Dán Tensaur',
        'white',
        'giay_tre_em',
        'thethao',
        7.0,
        ['Giày Tập Thể Thao Có Quai Dán Tensaur.jpg'],
        38,
    ),
    Data(
        8,
        'Giày FortaRun Sport Running Có Dây Giày Và Quai Dán',
        'black',
        'giay_tre_em',
        'thethao',
        13.5,
        ['Giày FortaRun Sport Running Có Dây Giày Và Quai Dán.jpg'],
        37,
    ),
    Data(9, 'Giày NMD_R1', 'white', 'giay_nam', 'originals', 53.5, ['Giày NMD_R1.jpg'], 41),
    Data(10, 'ZX 8000 LEGO', 'yellow', 'giay_nam', 'originals', 9.99, ['ZX 8000 LEGO1.jpg'], 42),
    Data(11, 'COPA SENSE.1 FG', 'yellow', 'giay_nam', 'bongda', 45.99, ['COPA SENSE.1 FG.jpg'], 43),
    Data(12, 'ADIZERO BOSTON 11 M', 'yellow', 'giay_nam', 'chạy', 69.99, ['ADIZERO BOSTON 11 M.jpg'], 44),
    Data(13, 'Giày NMD_R1', 'blue', 'giay_nam', 'originals', 13.99, ['Giày NMD_R11.jpg'], 41),
    Data(
        14,
        'Giày Ultraboost 1.0 DNA Running Sportswear Lifestyle',
        'black',
        'giay_nu',
        'thethao',
        119.99,
        ['Giày Ultraboost 1.0 DNA Running Sportswear Lifestyle.jpg'],
        37,
    ),
    Data(15, 'Giày Puremotion', 'white', 'giay_nu', 'thethao', 19.99, ['Giày Puremotion.jpg'], 39),
    Data(16, 'Giày Galaxy 6', 'white', 'giay_nu', 'chạy', 39.55, ['Giày Galaxy 6.jpg'], 37),
    Data(
        17,
        'Giày Ozelle Lifestyle Running Cloudfoam',
        'white',
        'giay_nu',
        'thethao',
        69.99,
        ['Giày Ozelle Lifestyle Running Cloudfoam.jpg'],
        38,
    ),
    Data(18, 'GIÀY ULTRABOOST 22', 'red', 'giay_nu', 'thethao', 29.99, ['GIÀY ULTRABOOST 22.jpg'], 38),
    Data(19, 'Giày Fluidflow 2.0', 'white', 'giay_nu', 'thethao', 69.99, ['Giày Fluidflow 2.0.jpg'], 39),
    Data(20, 'Giày Pureboost 22', 'blue', 'giay_nam', 'chạy', 59.99, ['Giày Pureboost 22.jpg'], 42),
    Data(21, 'Giày Tennis Barricade', 'blue', 'giay_nam', 'quanvot', 73.99, ['Giày Tennis Barricade.jpg'], 44),
    Data(
        22,
        'Giày Jeremy Scott Motorsport Wings 4.0',
        'blue',
        'giay_nam',
        'originals',
        35.99,
        ['Giày Jeremy Scott Motorsport Wings 4.0.jpg'],
        41,
    ),
    Data(23, 'FORUM 84 LOW 8K', 'blue', 'giay_nam', 'originals', 22.99, ['FORUM 84 LOW 8K.jpg'], 41),
    Data(24, 'Giày 4D Fusio', 'blue', 'giay_nam', 'originals', 43.99, ['Giày 4D Fusio.jpg'], 42),
    Data(25, 'Giày Supernova Tokyo', 'blue', 'giay_nam', 'chạy', 53.99, ['Giày Supernova Tokyo.jpg'], 44),
    Data(26, 'Giày Slip-On Nizza Pride', 'red', 'giay_nam', 'originals', 35.99, ['Giày Slip-On Nizza Pride.jpg'], 41),
    Data(27, 'Giày Ultraboost DNA', 'red', 'giay_nam', 'chạy', 33.99, ['Giày Ultraboost DNA1.jpg'], 43),
    Data(
        28,
        'Giày bongda Sân Cỏ Tự Nhiên Không Dây Predator Freak.3',
        'red',
        'giay_nam',
        'bongda',
        105.99,
        ['Giày bongda Sân Cỏ Tự Nhiên Không Dây Predator Freak 3.jpg'],
        40,
    ),
    Data(
        29,
        'Giày Tennis Adizero Ubersonic 4',
        'red',
        'giay_nam',
        'quanvot',
        15.99,
        ['Giày Tennis Adizero Ubersonic 41.jpg'],
        41,
    ),
    Data(30, 'Giày Adistar', 'white', 'giay_nam', 'chạy', 35.99, ['Giày Adistar.jpg'], 41),
    Data(
        31,
        'Giày adidas Grand Court x LEGO® 2.0',
        'white',
        'giay_nam',
        'thethao',
        95.99,
        ['Giày adidas Grand Court x LEGO® 2.0.jpg'],
        43,
    ),
    Data(32, 'Giày Lite Racer 3.0', 'black', 'giay_nu', 'thethao', 25.99, ['Giày Lite Racer 3.0.jpg'], 39),
    Data(33, 'Giày Harden Vol. 6', 'red', 'giay_nu', 'bongro', 75.99, ['Giày Harden Vol. 6.jpg'], 38),
    Data(34, 'Giày Solarcontrol', 'red', 'giay_nu', 'chạy', 65.99, ['Giày Solarcontrol.jpg'], 37),
    Data(35, 'Giày Ultraboost DNA', 'red', 'giay_nu', 'chạy', 55.99, ['Giày Ultraboost DNA.jpg'], 38),
    Data(
        36,
        'Giày Tennis Adizero Ubersonic 4',
        'yellow',
        'giay_nu',
        'quanvot',
        45.99,
        ['Giày Tennis Adizero Ubersonic 4.jpg'],
        38,
    ),
    Data(
        37,
        'Giày Climacool Vento HEAT.RDY',
        'yellow',
        'giay_nu',
        'chạy',
        19.99,
        ['Giày Climacool Vento HEAT.RDY.jpg'],
        39,
    ),
    Data(38, 'ZX 8000 LEGO', 'yellow', 'giay_nu', 'originals', 65.65, ['ZX 8000 LEGO.jpg'], 39),
    Data(39, 'Giày Bryony', 'yellow', 'giay_nu', 'originals', 99.99, ['Giày Bryony.jpg'], 37),
    Data(40, 'Giày Dame 8', 'blue', 'giay_nu', 'bongro', 35.99, ['Giày Dame 8.jpg'], 39),
    Data(41, 'Giày Forum Mid', 'blue', 'giay_nu', 'originals', 88.88, ['Giày Forum Mid.jpg'], 38),
    Data(42, 'Giày SL20', 'blue', 'giay_nu', 'chạy', 77.77, ['Giày SL20.jpg'], 39),
    Data(43, 'Giày Adizero Boston 9', 'blue', 'giay_nu', 'chạy', 55.55, ['Giày Adizero Boston 9.jpg'], 38),
    Data(44, 'Giày Dame 8', 'blue', 'giay_nu', 'bongro', 66.66, ['Giày Dame 81.jpg'], 37),
];
